### ISSUE TITLE
Ungueltiger Link im Readme

### ISSUE THREAD

**Issue by Izamii** [dabrowskiw/Template-Programmieren2-Aufgabe0#1]
Der Link zu _"[Arbeiten mit github classroom und zu github actions](https://mediathek.htw-berlin.de/video/Programmieren-2-Github-und-github-classroom/036e3b2487ed69492f4f31320e79fa3a)"_ scheint nicht mehr zu existieren bzw. müsste erneuert werden.

**Comment by dabrowskiw** [comment]
Vielen Dank für den Hinweis, jetzt müsste das Video aufrufbar sein (unter dem gleichen Link).
